/*
 * Sample API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi




type CountResponse struct {

	// カウント数
	Count int32 `json:"count,omitempty"`
}

// AssertCountResponseRequired checks if the required fields are not zero-ed
func AssertCountResponseRequired(obj CountResponse) error {
	return nil
}

// AssertCountResponseConstraints checks if the values respects the defined constraints
func AssertCountResponseConstraints(obj CountResponse) error {
	return nil
}
