version: '3.8'
services:
  go:
    image: golang:latest
    working_dir: /go
    volumes:
      - ./go:/go
    ports:
      - "8080:8080"
    environment:
      - GO111MODULE=on
    tty: true

  react:
    image: node:14.18.0
    working_dir: /react
    volumes:
      - ./react:/react
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    command: bash -c "cd /react && npm start"
    tty: true

  mysql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=mydatabase
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  mysql_data:
