version: '3.8'
services:
  go:
    build: 
      context: ./go
    volumes:
      - ./go:/app
      - ./openapi.yml:/api-spec/openapi.yml
    ports:
      - "8080:8080"
    environment:
      - TZ=Asia/Tokyo
    depends_on:
      - mysql
    tty: true

  react:
    image: node:14.18.0
    working_dir: /app
    volumes:
      - ./react:/app
      - ./openapi.yml:/api-spec/openapi.yml
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - TZ=Asia/Tokyo
    command: bash -c "cd /app && npm start"
    depends_on:
      - mysql
    tty: true

  mysql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=mydatabase
      - TZ=Asia/Tokyo
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  mysql_data:
