openapi: 3.0.0
info:
  title: Sample API
  version: 1.0.0
paths:
  /api/users/count:
    get:
      summary: ユーザー数を取得
      description: 登録されているユーザーの総数を返します。
      responses:
        '200':
          description: ユーザー数の取得に成功しました。
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CountResponse'
        '500':
          description: 内部サーバーエラーが発生しました。

  /api/microposts/count:
    get:
      summary: マイクロポスト数を取得
      description: 登録されているマイクロポストの総数を返します。
      responses:
        '200':
          description: マイクロポスト数の取得に成功しました。
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CountResponse'
        '500':
          description: 内部サーバーエラーが発生しました。

  /api/users:
    get:
      summary: ユーザー一覧を取得
      description: 登録されているすべてのユーザーの一覧を返します。
      responses:
        '200':
          description: ユーザー一覧の取得に成功しました。
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
        '500':
          description: 内部サーバーエラーが発生しました。

  /api/microposts:
    get:
      summary: マイクロポスト一覧を取得
      description: 登録されているすべてのマイクロポストの一覧を返します。
      responses:
        '200':
          description: マイクロポスト一覧の取得に成功しました。
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Micropost'
        '500':
          description: 内部サーバーエラーが発生しました。

components:
  schemas:
    CountResponse:
      type: object
      properties:
        count:
          type: integer
          example: 123
          description: カウント数
    User:
      type: object
      properties:
        id:
          type: integer
          description: ユーザーのID
          example: 1
        name:
          type: string
          description: ユーザーの名前
          example: "山田太郎"
        email:
          type: string
          format: email
          description: ユーザーのメールアドレス
          example: "yamada@example.com"
        createdAt:
          type: string
          format: date-time
          description: アカウントの作成日時
          example: "2021-01-01T12:00:00Z"
        updatedAt:
          type: string
          format: date-time
          description: アカウントの更新日時
          example: "2021-06-01T15:00:00Z"
    Micropost:
      type: object
      properties:
        id:
          type: integer
          description: マイクロポストのID
          example: 101
        content:
          type: string
          description: マイクロポストの内容
          example: "これはサンプルのマイクロポストです。"
        userId:
          type: integer
          description: 作成したユーザーのID
          example: 1
        createdAt:
          type: string
          format: date-time
          description: マイクロポストの作成日時
          example: "2021-01-02T10:00:00Z"
        updatedAt:
          type: string
          format: date-time
          description: マイクロポストの更新日時
          example: "2021-06-02T18:00:00Z"
        user:
          $ref: '#/components/schemas/User'
