openapi: 3.0.0
info:
  title: Sample API
  version: 1.0.0
paths:
  /api/users/count:
    get:
      summary: ユーザー数を取得
      description: 登録されているユーザーの総数を返します。
      responses:
        '200':
          description: ユーザー数の取得に成功しました。
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CountResponse'
        '500':
          description: 内部サーバーエラーが発生しました。

  /api/microposts/count:
    get:
      summary: マイクロポスト数を取得
      description: 登録されているマイクロポストの総数を返します。
      responses:
        '200':
          description: マイクロポスト数の取得に成功しました。
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CountResponse'
        '500':
          description: 内部サーバーエラーが発生しました。

components:
  schemas:
    CountResponse:
      type: object
      properties:
        count:
          type: integer
          example: 123
          description: カウント数
