openapi: 3.0.0
info:
  title: Sample API
  version: 1.0.0
servers:
- url: /
paths:
  /api/users/count:
    get:
      description: 登録されているユーザーの総数を返します。
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CountResponse'
          description: ユーザー数の取得に成功しました。
        "500":
          description: 内部サーバーエラーが発生しました。
      summary: ユーザー数を取得
  /api/microposts/count:
    get:
      description: 登録されているマイクロポストの総数を返します。
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CountResponse'
          description: マイクロポスト数の取得に成功しました。
        "500":
          description: 内部サーバーエラーが発生しました。
      summary: マイクロポスト数を取得
components:
  schemas:
    CountResponse:
      example:
        count: 123
      properties:
        count:
          description: カウント数
          example: 123
          type: integer
      type: object
