// Code generated by ogen, DO NOT EDIT.

package ogen

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// APIMicropostsCountGet implements GET /api/microposts/count operation.
//
// 登録されているマイクロポストの総数を返します。.
//
// GET /api/microposts/count
func (UnimplementedHandler) APIMicropostsCountGet(ctx context.Context) (r APIMicropostsCountGetRes, _ error) {
	return r, ht.ErrNotImplemented
}

// APIUsersCountGet implements GET /api/users/count operation.
//
// 登録されているユーザーの総数を返します。.
//
// GET /api/users/count
func (UnimplementedHandler) APIUsersCountGet(ctx context.Context) (r APIUsersCountGetRes, _ error) {
	return r, ht.ErrNotImplemented
}
