// Code generated by ogen, DO NOT EDIT.
package ogen

type APIMicropostsCountGetRes interface {
	aPIMicropostsCountGetRes()
}

type APIMicropostsGetRes interface {
	aPIMicropostsGetRes()
}

type APIUsersCountGetRes interface {
	aPIUsersCountGetRes()
}

type APIUsersGetRes interface {
	aPIUsersGetRes()
}
